language: node_js

node_js:
  - "lts/*"
  - "10"
  - "8"

install:
  - yarn
  - yarn global add codecov

cache:
  yarn: true
  directories:
    - "node_modules"
    - ".cache"

script:
  - yarn format
  - yarn lint
  - yarn test
  - yarn build
  - codecov
