language: node_js

node_js:
  - "node"
  - "8"
  - "10"

install:
  - yarn
  - yarn global add codecov

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn format
  - yarn lint
  - yarn test
  - yarn build
  - codecov
